#LOCAL SERVER
#스마투스 일반 앱 로컬 설정
spring:
    profiles:
        active: local


    #datasource (mariaDB)
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        #운영서버 Prod Database
        db-url: jdbc:log4jdbc:mariadb://localhost:3306/smartooth
        db-username: smartooth
        db-password: smartooth509#

        
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
        static-path-pattern : /static/**

        
    #메일 발송 부분은 로직은 동일, 메일 발송 HOST, ID, 비밀번호만 변경해주면 됨
    mailsendername: Smartooth KOREA
    mailusername: manager@smartooth.co
    mailpassword: dkagh1505!@
  
  
    mybatis:
        configuration:
            map-underscore-to-camel-case: 'true'


    jwt:
        secretKey: tmakxntmzhfldk
        
        
    web:
        resources:
            static-locations : classpath:/static-location/
---
spring:
    server:
        #로컬 local
        ip: localhost
        port: 8080

            
#---
#spring:
#    web:
#        resources:
#            add-mappings: 'true'